name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: make sdepsinstall

    - name: Build app
      run: make

    - name: Convert app
      run: make sconvert ARGS="app.zip"

    - name: Run app
      run: make srun ARGS="app.zip"
